import React from 'react';

// Feather icon replacements
export const FiMail = (props: any) => <span className={props.className}>📧</span>;
export const FiLock = (props: any) => <span className={props.className}>🔒</span>;
export const FiAlertCircle = (props: any) => <span className={props.className}>⚠️</span>;
export const FiUser = (props: any) => <span className={props.className}>👤</span>;
export const FiMenu = (props: any) => <span className={props.className}>☰</span>;
export const FiX = (props: any) => <span className={props.className}>✖</span>;
export const FiMoon = (props: any) => <span className={props.className}>🌙</span>;
export const FiSun = (props: any) => <span className={props.className}>☀️</span>;
export const FiLogOut = (props: any) => <span className={props.className}>🚪</span>;
export const FiArrowLeft = (props: any) => <span className={props.className}>←</span>;
export const FiEdit2 = (props: any) => <span className={props.className}>✏️</span>;
export const FiSave = (props: any) => <span className={props.className}>💾</span>;
export const FiTrash2 = (props: any) => <span className={props.className}>🗑️</span>;
export const FiUpload = (props: any) => <span className={props.className}>⬆️</span>;
export const FiFile = (props: any) => <span className={props.className}>📄</span>;
export const FiFileText = (props: any) => <span className={props.className}>📝</span>;
export const FiCpu = (props: any) => <span className={props.className}>🖥️</span>;
export const FiTwitter = (props: any) => <span className={props.className}>🐦</span>;
export const FiMessageSquare = (props: any) => <span className={props.className}>💬</span>;
export const FiPlus = (props: any) => <span className={props.className}>➕</span>;
export const FiFolder = (props: any) => <span className={props.className}>📁</span>;
export const FiEdit = (props: any) => <span className={props.className}>✏️</span>;
export const FiTrash = (props: any) => <span className={props.className}>🗑️</span>;
export const FiCheck = (props: any) => <span className={props.className}>✅</span>;
export const FiStar = (props: any) => <span className={props.className}>⭐</span>;
export const FiZap = (props: any) => <span className={props.className}>⚡</span>;
export const FiShield = (props: any) => <span className={props.className}>🛡️</span>;
export const FiHeadphones = (props: any) => <span className={props.className}>🎧</span>; 